name: Issue Assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: 'Auto-assign Issue'
        uses: pozil/auto-assign-issue@v2.2.0
        with:
          assignees: sejongjeong, yjinheon, ryeong0418, kyungjunleeme, gyfla810, ggaem
          numOfAssignee: 2
          allowSelfAssign: false
